zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    profile-service:
      path: /users/**
      serviceId: PROFILE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: api-gateway-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000